language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"

# Cache pip-installed dependencies
cache:
    pip: true

services:
  - xvfb

env:
  - PYUVDATA_VERSION=""
  #- PYUVDATA_VERSION="@d6e1c2f80d7b5b59d7794c8f28d867a7030a7c75"

#allow_failures:
#  - env: PYUVDATA_VERSION=""

install:
  # ensure that we have the full tag information available for version.py
  - git fetch --tags
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # create environment and install dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coveralls
  - source activate test-environment
  - conda env update -n test-environment -f environment.yml
  - pip install git+https://github.com/HERA-Team/linsolve.git #only required till it updates
  - pip install git+https://github.com/HERA-Team/uvtools.git #only required till it updates
  - pip install git+https://github.com/HERA-Team/hera_cal.git
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install scikit-learn==0.20.3;
    else
      pip install scikit-learn;
    fi
  - pip install .

before_script:
  - "export MPLBACKEND=agg"

script: nosetests hera_pspec --with-coverage --cover-package=hera_pspec --verbose

after_success:
  - coveralls
