name: Run Tests
 
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11"]
      fail-fast: false

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip install .[dev]

    - name: Run Tests
      run: |
        export MPLBACKEND=agg
        pytest --cov=hera_pspec --cov-config="./.coveragerc" \
               --cov-report xml:"./coverage.xml" --junitxml="./test-reports/xunit.xml"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
